# -*- coding: utf-8 -*-
"""iris_svm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1avO2_N3zSchgfdKRY-s605ztYgojZFji
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

iris = datasets.load_iris()

X = iris.data
y = iris.target

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

model = SVC(kernel='linear')

model.fit(X_train, y_train)

print("SVM model trained successfully!")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# Example new sample: [sepal length, sepal width, petal length, petal width]
new_sample = [[5, 3,3, 0.2]]

prediction = model.predict(new_sample)

print("Predicted class:", prediction[0])
print("Flower name:", iris.target_names[prediction[0]])







